### ISSUE TITLE
Mistake in documentation for "Define routes manually"

### ISSUE THREAD

**Issue by j-sharpmoon** [marcin-jozwikowski/easy-admin-pretty-urls#19]
Hi Marcin,

Thanks for working on this bundle.  I discovered from troubleshooting & the app error log that your documentation does not match the code behavior. I'm using your v2.3.0 with Symfony 6.3.1.

Currently, your instructions state: "Route name must match the pattern <prefix>_<name>_<action> with <action> equal to crudAction and <name> being the target controller class name (not FQCN - just the last part) **_stripped of Crud_** and Controller, written in snake_case. <prefix> is set to pretty by default. See Configuration to ways to change it."

But in fact the "_crud_" part MUST be in the route name to work, at least in my case.  I have an EasyAdmin controller called SiteCrudController and when I tried using the route name of "pretty_site_index" it completely failed, throwing this exception: 'Unable to generate a URL for the named route "easyadmin" as such route does not exist.'

But after renaming it to "pretty_site_crud_index" it works as expected.

**Comment by marcin-jozwikowski** [comment]
Hi @j-sharpmoon
Thanks a lot for pointing that out.

I've fixed the docs and already released it as 2.3.0.

A change in route names generation is something I had on my mind for some time now, but I honestly don't know when I'll be able to add it.
I hope that the way it works now is good enough, especially now, that the docs are correct.
