### ISSUE TITLE
"referrer" query param is added to every link inside easyadmin

### ISSUE THREAD

**Issue by sarim** [marcin-jozwikowski/easy-admin-pretty-urls#22]
for example add button 

https://localhost/card_crud/new?referrer=https://localhost/card_crud/index

**Comment by marcin-jozwikowski** [comment]
Hi @sarim,

That is something that EasyAdmin does by itself.
It is parsed by the plugin and made into a pretty URL but it was put there by the EA itself in the first place.

The referrer is used in all 'Back' buttons.
