### ISSUE TITLE
Association null lable not visible

### ISSUE THREAD

**Issue by stealth-program** [marcin-jozwikowski/easy-admin-pretty-urls#24]
![image](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/assets/22191152/ca11ce68-be1e-48dd-a9f0-e08dd0c41123)
If field is association, value is null, there is nothing visible
AdminBundle 4.8.6

**Comment by marcin-jozwikowski** [comment]
Isn't that a default EasyAdmin behavior?

I think that [formatting options](https://symfony.com/bundles/EasyAdminBundle/current/fields.html#formatting-options) for fields might be of help in that.

**Comment by stealth-program** [comment]
@marcin-jozwikowski nope,  default EasyAdmin behaviour is null lable with null.twig template
![image](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/assets/22191152/79003b6e-71d7-4393-b78b-31898c723bbc)

**Comment by marcin-jozwikowski** [comment]
Got it fixed in latest release [v.2.4.2](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.4.2)
![image](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/assets/5331237/2437d051-6b0b-401e-b635-3827ba0a3124)
