### ISSUE TITLE
Menu items broke with EA 4.11.0

### ISSUE THREAD

**Issue by Geolim4** [marcin-jozwikowski/easy-admin-pretty-urls#41]
Hello Marcin,

I think there's an incompatibility with the latest minor release of EA:
https://github.com/EasyCorp/EasyAdminBundle/releases/tag/v4.11.0

Especially this one:
https://github.com/EasyCorp/EasyAdminBundle/commit/1fc89fd02fbe72bd7d3b632b75e432795c49b910

I have no longer highlighted menu items and I think it is related onw how the new `getControllersAndActionsLinkedInTheMenu` is working and reading the HTTP query parameters.
https://github.com/EasyCorp/EasyAdminBundle/commit/1fc89fd02fbe72bd7d3b632b75e432795c49b910#diff-28161240fad2f846bb63f7dd490ddfef972ba7e15db1b3b0f358424ba43a844aR186

Nothing urgent, but if you have some free time to take a look at it, it would be welcomed !

Georges

**Comment by mareklauko** [comment]
Just working idea:

`<?php
declare(strict_types=1);

namespace App\Manager;

use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Option\EA;
use EasyCorp\Bundle\EasyAdminBundle\Dto\MenuItemDto;
use EasyCorp\Bundle\EasyAdminBundle\Menu\MenuItemMatcher;
use Symfony\Component\HttpFoundation\Request;

final class PrettyMenuItemMatcher extends MenuItemMatcher
{
    /**
     * Given the full list of menu items, this method finds which item should be
     * marked as 'selected' based on the current page being visited by the user.
     * If the selected item is a submenu item, it also marks the parent menu item
     * as 'expanded'.
     *
     * It returns the full list of menu items, including the updated item(s) marked
     * as selected/expanded.
     *
     * @param MenuItemDto[] $menuItems
     *
     * @return MenuItemDto[]
     */
    public function markSelectedMenuItem(array $menuItems, Request $request): array
    {
        $menuItems = $this->doMarkSelectedMenuItem($menuItems, $request);
        $menuItems = $this->doMarkExpandedMenuItem($menuItems);

        return $menuItems;
    }

    /**
     * @param MenuItemDto[] $menuItems
     *
     * @return MenuItemDto[]
     */
    private function doMarkSelectedMenuItem(array $menuItems, Request $request): array
    {
        // the menu-item matching is a 2-phase process:
        // 1) scan all menu items to list which controllers and actions are linked from the menu;
        //    this is needed because e.g. sometimes we match a menu item that doesn't have the exact
        //    action but links to the INDEX action of the same controller of the current request
        // 2) decide which is the most appropriate menu item (if any) to mark as selected based on the current request
        $controllersAndActionsLinkedInTheMenu = $this->getControllersAndActionsLinkedInTheMenu($menuItems);
        $currentPagePathParameters = explode('/', ltrim($request->getPathInfo(), '/'));
        $currentRequestUri = $request->getUri();

        foreach ($menuItems as $menuItemDto) {
            if ($menuItemDto->isMenuSection()) {
                continue;
            }

            if ([] !== $subItems = $menuItemDto->getSubItems()) {
                $menuItemDto->setSubItems($this->doMarkSelectedMenuItem($subItems, $request));
            }

            $menuItemQueryString = null === $menuItemDto->getLinkUrl() ? null : parse_url($menuItemDto->getLinkUrl(), \PHP_URL_PATH);
            if (null === $menuItemQueryString) {
                continue;
            }
            $menuItemPathParameters = explode('/', ltrim($menuItemQueryString, '/'));

            if ([] === $menuItemPathParameters || [] === $currentPagePathParameters) {
                if ($menuItemDto->getLinkUrl() === $currentRequestUri) {
                    $menuItemDto->setSelected(true);
                }

                break;
            }

            // if the menu only contains links to the INDEX action of the CRUD controller,
            // match that menu item for all actions (EDIT, NEW, etc.) of the same controller;
            // this is not strictly correct, but backend users expect this behavior because it
            // makes the sidebar menu more predictable and easier to use
            $menuItemController = $menuItemPathParameters[0] ?? null;
            $currentPageController = $currentPagePathParameters[0] ?? null;
            $actionsLinkedInTheMenuForThisEntity = $controllersAndActionsLinkedInTheMenu[$currentPageController] ?? [];
            $menuOnlyLinksToIndexActionOfThisEntity = $actionsLinkedInTheMenuForThisEntity === [Crud::PAGE_INDEX];
            if ($menuItemController === $currentPageController && $menuOnlyLinksToIndexActionOfThisEntity) {
                $menuItemDto->setSelected(true);

                break;
            }

            // if the menu contains links to more than one action of the CRUD controller
            // (e.g. INDEX and NEW), and the action of the current page is not included
            // in that list, match the menu item with the INDEX action; this is again not
            // strictly correct, but it's the expected behavior by backend users
            $menuItemAction = $menuItemPathParameters[0] ?? null;
            $currentPageAction = $currentPagePathParameters[0] ?? null;
            $isCurrentPageActionLinkedInTheMenu = \in_array($currentPageAction, $actionsLinkedInTheMenuForThisEntity, true);
            if ($menuItemController === $currentPageController && Crud::PAGE_INDEX === $menuItemAction && !$isCurrentPageActionLinkedInTheMenu) {
                $menuItemDto->setSelected(true);

                break;
            }

            // otherwise, match the query parameters of each menu item with the query
            // parameters of the current request; before making the match, we remove
            // some irrelevant query parameters such as filters, sorting, pagination, etc.
            $menuItemQueryParametersToCompare = $this->filterIrrelevantQueryParameters($menuItemPathParameters);
            $currentPageQueryParametersToCompare = $this->filterIrrelevantQueryParameters($currentPagePathParameters);

            // needed so you can pass route parameters in any order
            $this->recursiveKsort($menuItemQueryParametersToCompare);
            $this->recursiveKsort($currentPageQueryParametersToCompare);

            if ($menuItemQueryParametersToCompare === $currentPageQueryParametersToCompare) {
                $menuItemDto->setSelected(true);

                break;
            }
        }

        return $menuItems;
    }

    /**
     * Given the full list of menu items, this method finds which item should be
     * marked as expanded because any of its items is currently selected and
     * updates it.
     *
     * @param MenuItemDto[] $menuItems
     *
     * @return MenuItemDto[]
     */
    private function doMarkExpandedMenuItem(array $menuItems): array
    {
        foreach ($menuItems as $menuItemDto) {
            if ([] === $menuSubitems = $menuItemDto->getSubItems()) {
                continue;
            }

            foreach ($menuSubitems as $submenuItem) {
                if ($submenuItem->isSelected()) {
                    $menuItemDto->setExpanded(true);

                    break;
                }
            }
        }

        return $menuItems;
    }

    /**
     * It scans the full list of menu items to find which controllers and actions
     * are linked from the menu. The output is something like:
     * [
     *     'App\Controller\Admin\BlogPostCrudController' => ['index', 'new'],
     *     'App\Controller\Admin\BlogCategoryCrudController' => ['index'],
     *     // ...
     *     'App\Controller\Admin\UserCrudController' => ['index', 'new'],
     * ].
     *
     * @return array<string, array<string>>
     */
    private function getControllersAndActionsLinkedInTheMenu(array $menuItems): array
    {
        $controllersAndActionsLinkedInTheMenu = [];
        foreach ($menuItems as $menuItemDto) {
            if ($menuItemDto->isMenuSection()) {
                continue;
            }

            if ([] !== $subItems = $menuItemDto->getSubItems()) {
                $controllersAndActionsLinkedInTheMenu = array_merge_recursive($controllersAndActionsLinkedInTheMenu, $this->getControllersAndActionsLinkedInTheMenu($subItems));

                continue;
            }

            $menuItemQueryString = null === $menuItemDto->getLinkUrl() ? null : parse_url($menuItemDto->getLinkUrl(), \PHP_URL_PATH);
            if (null === $menuItemQueryString) {
                continue;
            }
            $menuItemPathParameters = explode('/', ltrim($menuItemQueryString, '/'));

            $controllerFqcn = $menuItemPathParameters[0] ?? null;
            $crudAction = $menuItemPathParameters[1] ?? Crud::PAGE_INDEX;
            if (null === $controllerFqcn) {
                continue;
            }

            if (isset($controllersAndActionsLinkedInTheMenu[$controllerFqcn])) {
                $controllersAndActionsLinkedInTheMenu[$controllerFqcn][] = $crudAction;
            } else {
                $controllersAndActionsLinkedInTheMenu[$controllerFqcn] = [$crudAction];
            }
        }

        return $controllersAndActionsLinkedInTheMenu;
    }

    /*
     * Sorts an array recursively by its keys. This is needed because some values
     * of the array with the query string parameters can be arrays too, and we must
     * sort those before the comparison.
     */
    private function recursiveKsort(&$array): void
    {
        if (!\is_array($array)) {
            return;
        }

        ksort($array);

        foreach ($array as &$value) {
            if (\is_array($value)) {
                $this->recursiveKsort($value);
            }
        }
    }

    /**
     * Removes from the given list of query parameters all the parameters that
     * should be ignored when deciding if some menu item matches the current page
     * (such as the applied filters or sorting, the listing page number, etc.).
     */
    private function filterIrrelevantQueryParameters(array $queryStringParameters): array
    {
        $paramsToRemove = [EA::REFERRER, EA::PAGE, EA::FILTERS, EA::SORT];

        return array_filter($queryStringParameters, static fn ($k) => !\in_array($k, $paramsToRemove, true), \ARRAY_FILTER_USE_KEY);
    }

}`

`
  EasyCorp\Bundle\EasyAdminBundle\Menu\MenuItemMatcher:
    class: App\Manager\PrettyMenuItemMatcher
`

**Comment by Geolim4** [comment]
Thanks @mareklauko

It works almost perfeclty: new/detail/edit actions are ignored by the MenuMatcher if they have been customized.

Example:

Working: (index)
https://127.0.0.1:8000/admin-xxxxxx/animaux-entres/

Not working 😅 (edit/detail/new)
https://127.0.0.1:8000/admin-xxxxxx/animaux-entres/edit/0190f967-01fd-7a04-bd64-2758055b5302
https://127.0.0.1:8000/admin-xxxxxx/animaux-entres/view/0190f967-01fd-7a04-bd64-2758055b5302
https://127.0.0.1:8000/admin-xxxxxx/animaux-entres/new

**Comment by Geolim4** [comment]
Managed to get it working by improving your code with the following one;

Replace:

```php
            if ($menuItemQueryParametersToCompare === $currentPageQueryParametersToCompare) {
                $menuItemDto->setSelected(true);

                break;
            }
```
By:
```php
            $filteredMenuItemQueryParametersToCompare = array_filter($menuItemQueryParametersToCompare);
            $filteredCurrentPageQueryParametersToCompare = array_filter($currentPageQueryParametersToCompare);
            if (
                (count($filteredMenuItemQueryParametersToCompare) > 1 && !array_diff($filteredMenuItemQueryParametersToCompare, $filteredCurrentPageQueryParametersToCompare))
                || (count($filteredMenuItemQueryParametersToCompare) === 1 && $menuItemQueryParametersToCompare === $currentPageQueryParametersToCompare)
            ) {
                $menuItemDto->setSelected(true);

                break;
            }
```

**Comment by Geolim4** [comment]
The code is, indeed, a bit too much verbose and maybe phpcs inconsistent, but feel free to improve it @marcin-jozwikowski :D

**Comment by marcin-jozwikowski** [comment]
@Geolim4 @mareklauko Thank you very much for this! I truly appreciate you work and contribution.

I'll implement the changes as soon as I get back home from vacation - at the end of this week.

Cheers!

**Comment by marcin-jozwikowski** [comment]
@Geolim4 @mareklauko [v.2.9.0](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.9.0) should have fixed the problem.

Please, see if it did.

**Comment by Geolim4** [comment]
That's a hell of an update, will test it tomorrow, thanks !

**Comment by Geolim4** [comment]
Hello @marcin-jozwikowski it almost works perfectly except in one case:

When being on "admin_dashboard" it highlights me multiple other menu items.
I noticed that it highlights only the `MenuItem::subMenu()` and the `MenuItem::linkToUrl` items.

Links built with `MenuItem::linkToCrud` are working like a charm !

For the rest it work perfectly

**Comment by marcin-jozwikowski** [comment]
@Geolim4 Check out latest changes: https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.9.1

The comparison before that was trying to resolve all URLs and most non-crud just returned ['_locale' => '....'] and were counted as the same.
Now it's comparing just the URLs.

**Comment by Geolim4** [comment]
Perfect, working perfectly. Thank you Marcin !
