### ISSUE TITLE
Incoming update of EA

### ISSUE THREAD

**Issue by Geolim4** [marcin-jozwikowski/easy-admin-pretty-urls#47]
Hello Marcin,

Just to warn you something is moving on EA side:
https://github.com/EasyCorp/EasyAdminBundle/pull/6467

I'm just afraid that they will only harcode the entity name in the URL without getting as much flexible as your bundle.

If you can take a look/give some suggestion to @javiereguiluz

**Comment by Geolim4** [comment]
@marcin-jozwikowski I think you can update your composer.json to put a version constraint, EA implemented Pretty Urls:
https://github.com/EasyCorp/EasyAdminBundle/releases/tag/v4.14.0

You did a great job for Easy Admin Marcin, thank you for releasing this to the community !

**Comment by marcin-jozwikowski** [comment]
Yeah, I'll have to.
Thanks a lot for your help here! I couldn't have done that just by myself!
I'm glad our work here gave EA people the idea to implement clean URLs into their solution.

**Comment by marcin-jozwikowski** [comment]
[v2.9.3](https://github.com/marcin-jozwikowski/easy-admin-pretty-urls/releases/tag/v2.9.3) limits the EA version.

You can update EA without updating this bundle, but there's little I can do to stop that.
